version: '3.8'

services:
  appapigateway:
    build:
      context: .
    command: bash start-dev.sh
    ports:
      - "8080:8080"
      - "5008:5005"
    environment:
      GRADLE_USER_HOME: /box
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - .:/api-gateway
      - boxapigateway:/box
    networks:
      - ead-microservices-net
  boxapigateway:
    image: busybox
    volumes:
      - /box
    networks:
      - ead-microservices-net
networks:
  ead-microservices-net:
    name: ead-microservices-net
    external: true
volumes:
  boxapigateway: